### ISSUE TITLE
Error of training MANet

### ISSUE THREAD

**Issue by Leedeng** [VUT-HFUT/Micro-Action#2]
```
FileNotFoundError: VideoDataset: [Errno 2] No such file or directory: '/chenguoliang/code/mmaction2/manet/1214_new_mean_Vectors.npy'
```
Could you provide this file "1214_new_mean_Vectors.npy"?

**Comment by kunli-cs** [comment]
Hi Leedeng. This file is in "mar_scripts/manet/mmaction2/manet/1214_new_mean_Vectors.npy". You need to change the path. 
If you have any questions, please feel free to contact me.
